.TH "dirh" 1 "16 Jun 2009" "Version 1.23.1" "fish" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dirh - print directory history
.PP
.SS "Synopsis"
\fCdirh\fP
.SS "Description"
\fCdirh\fP prints the current directory history. The current position in the history is highlighted using \fC$fish_color_history_current\fP. 
