.TH "fish_pager" 1 "16 Jun 2009" "Version 1.23.1" "fish" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fish_pager - internal command used by fish
.PP
.SS "Description"
This command is used internally by fish to display a list of completions. It should not be used by other commands, as it's interface is liable to change in the future. 
