.TH "funced" 1 "16 Jun 2009" "Version 1.23.1" "fish" \" -*- nroff -*-
.ad l
.nh
.SH NAME
funced - edit a function interactively
.PP
.SS "Synopsis"
\fCfunced NAME\fP
.SS "Description"
Use the funced command to interactively edit the definition of a function. If there is no function with the name specified, a skeleton function is inserted, if a function exist, the definion will be shown on the command line. 
