.TH "funcsave" 1 "16 Jun 2009" "Version 1.23.1" "fish" \" -*- nroff -*-
.ad l
.nh
.SH NAME
funcsave - save the definition of a function to the users autoload directory
.PP
.SS "Synopsis"
\fCfuncsave FUNCTION_NAME\fP
.SS "Description"
funcsave is used to save the current definition of a function to a file which will be autoloaded by current and future fish sessions. This can be useful if you have interactively created a new function and wish to save it for later use. 
