.TH "vared" 1 "16 Jun 2009" "Version 1.23.1" "fish" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vared - interactively edit the value of an environment variable
.PP
.SS "Synopsis"
\fCvared VARIABLE_NAME\fP
.SS "Description"
vared is used to interactively edit the value of an environment variable. Array variables as a whole can not be edited using vared, but individual array elements can.
.SS "Example"
\fCvared PATH[3]\fP edits the third element of the PATH array 
